---
- name: Configure standard ACL
  hosts: R1
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: Load new ACL into device
     ios_config:
       parents: ip access-list extended REQ2
       lines:
         - 10 permit icmp 192.168.20.20 host 192.168.10.10 echo-reply
         - 20 permit icmp 192.168.20.20 host any echo-reply
         - 30 deny icmp any host any echo-reply
         - 40 permit tcp any any
                  
   - name: Apply new ACL to R1 Eth0/0 out
     ios_config:
       parents: int e0/0
       lines:
         - ip access-group REQ2 out

   - name: Check result
     ios_command:
       commands: sh run
     register: result
     tags: show

   - name: Print result
     debug:
       var: result.stdout_lines
     tags: show
  
